// Copyright 2024 servex Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: auth/proto/auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MethodAuthOptions 方法级别的认证选项.
//
// 使用示例:
//
//	import "github.com/Tsukikage7/servex/auth/proto/auth.proto";
//
//	service AuthService {
//	  rpc Login(LoginRequest) returns (LoginResponse) {
//	    option (microservice.kit.auth.method) = {
//	      public: true
//	    };
//	  }
//
//	  rpc GetProfile(GetProfileRequest) returns (GetProfileResponse) {
//	    option (microservice.kit.auth.method) = {
//	      permissions: ["user:read"]
//	    };
//	  }
//	}
type MethodAuthOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public 标记该方法为公开接口，无需认证.
	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	// permissions 该方法需要的权限列表.
	// 用户必须拥有列表中的至少一个权限才能访问（OR 逻辑）.
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// all_permissions 是否需要拥有所有权限.
	// 默认 false（OR 逻辑），设为 true 时需要拥有所有权限（AND 逻辑）.
	AllPermissions bool `protobuf:"varint,3,opt,name=all_permissions,json=allPermissions,proto3" json:"all_permissions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MethodAuthOptions) Reset() {
	*x = MethodAuthOptions{}
	mi := &file_auth_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodAuthOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodAuthOptions) ProtoMessage() {}

func (x *MethodAuthOptions) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodAuthOptions.ProtoReflect.Descriptor instead.
func (*MethodAuthOptions) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *MethodAuthOptions) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *MethodAuthOptions) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MethodAuthOptions) GetAllPermissions() bool {
	if x != nil {
		return x.AllPermissions
	}
	return false
}

// ServiceAuthOptions 服务级别的认证选项.
//
// 使用示例:
//
//	service PublicService {
//	  option (microservice.kit.auth.service) = {
//	    public: true  // 该服务下所有方法都是公开的
//	  };
//	}
type ServiceAuthOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public 标记该服务下所有方法为公开接口.
	Public bool `protobuf:"varint,1,opt,name=public,proto3" json:"public,omitempty"`
	// default_permissions 服务下所有方法的默认权限要求.
	DefaultPermissions []string `protobuf:"bytes,2,rep,name=default_permissions,json=defaultPermissions,proto3" json:"default_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceAuthOptions) Reset() {
	*x = ServiceAuthOptions{}
	mi := &file_auth_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAuthOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuthOptions) ProtoMessage() {}

func (x *ServiceAuthOptions) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuthOptions.ProtoReflect.Descriptor instead.
func (*ServiceAuthOptions) Descriptor() ([]byte, []int) {
	return file_auth_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceAuthOptions) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *ServiceAuthOptions) GetDefaultPermissions() []string {
	if x != nil {
		return x.DefaultPermissions
	}
	return nil
}

var file_auth_proto_auth_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodAuthOptions)(nil),
		Field:         50001,
		Name:          "microservice.kit.auth.method",
		Tag:           "bytes,50001,opt,name=method",
		Filename:      "auth/proto/auth.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceAuthOptions)(nil),
		Field:         50002,
		Name:          "microservice.kit.auth.service",
		Tag:           "bytes,50002,opt,name=service",
		Filename:      "auth/proto/auth.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional microservice.kit.auth.MethodAuthOptions method = 50001;
	E_Method = &file_auth_proto_auth_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional microservice.kit.auth.ServiceAuthOptions service = 50002;
	E_Service = &file_auth_proto_auth_proto_extTypes[1]
)

var File_auth_proto_auth_proto protoreflect.FileDescriptor

const file_auth_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x15auth/proto/auth.proto\x12\x15microservice.kit.auth\x1a google/protobuf/descriptor.proto\"v\n" +
	"\x11MethodAuthOptions\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12'\n" +
	"\x0fall_permissions\x18\x03 \x01(\bR\x0eallPermissions\"]\n" +
	"\x12ServiceAuthOptions\x12\x16\n" +
	"\x06public\x18\x01 \x01(\bR\x06public\x12/\n" +
	"\x13default_permissions\x18\x02 \x03(\tR\x12defaultPermissions:b\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2(.microservice.kit.auth.MethodAuthOptionsR\x06method:f\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18҆\x03 \x01(\v2).microservice.kit.auth.ServiceAuthOptionsR\aserviceB0Z.github.com/Tsukikage7/servex/auth/proto;authpbb\x06proto3"

var (
	file_auth_proto_auth_proto_rawDescOnce sync.Once
	file_auth_proto_auth_proto_rawDescData []byte
)

func file_auth_proto_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_auth_proto_rawDesc), len(file_auth_proto_auth_proto_rawDesc)))
	})
	return file_auth_proto_auth_proto_rawDescData
}

var file_auth_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_proto_auth_proto_goTypes = []any{
	(*MethodAuthOptions)(nil),           // 0: microservice.kit.auth.MethodAuthOptions
	(*ServiceAuthOptions)(nil),          // 1: microservice.kit.auth.ServiceAuthOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_auth_proto_auth_proto_depIdxs = []int32{
	2, // 0: microservice.kit.auth.method:extendee -> google.protobuf.MethodOptions
	3, // 1: microservice.kit.auth.service:extendee -> google.protobuf.ServiceOptions
	0, // 2: microservice.kit.auth.method:type_name -> microservice.kit.auth.MethodAuthOptions
	1, // 3: microservice.kit.auth.service:type_name -> microservice.kit.auth.ServiceAuthOptions
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_auth_proto_init() }
func file_auth_proto_auth_proto_init() {
	if File_auth_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_auth_proto_rawDesc), len(file_auth_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_auth_proto_msgTypes,
		ExtensionInfos:    file_auth_proto_auth_proto_extTypes,
	}.Build()
	File_auth_proto_auth_proto = out.File
	file_auth_proto_auth_proto_goTypes = nil
	file_auth_proto_auth_proto_depIdxs = nil
}
